[package]
name = "fastdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
crc = "3.0.1"
glob = "0.3.1"
itertools = "0.10.5"
opencv = { version = "0.80.0", default-features = false, features = [
    "imgcodecs",
    "imgproc",
] }
# opencv = "0.80.0"
prost = "0.11.9"
rand = "0.8.5"
rayon = "1.7.0"
thiserror = "1.0.40"

[build-dependencies]
prost-build = "0.11.9"
