[package]
name = "fastdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
prost = "0.11.9"
thiserror = "1.0.40"

[build-dependencies]
prost-build = "0.11.9"
