[package]
name = "fastdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
crc = "3.0.1"
glob = "0.3.1"
libvips = "1.5.1"
prost = "0.11.9"
rayon = "1.7.0"
thiserror = "1.0.40"

[build-dependencies]
prost-build = "0.11.9"
